In [1]:
import os

In [8]:
import numpy as np
tmp = np.array(os.listdir('all'))
len(tmp)

3943

In [10]:
import random
val = [i for i in range(len(tmp))]
x = np.array(random.sample(val, 54))
tmp[x]

array(['mlp_bs128_1gpu_layer3_transtalklinear_talkmodedense_num64_messagews_sparsity0.132569_p0.005917_aggsum_graphseed6_starttrainseed1_endtrainseed6_keepTrue_add1x10_upperTrue_matchTrue_epoch200.yaml',
       'mlp_bs128_1gpu_layer3_transtalklinear_talkmodedense_num64_messagews_sparsity0.168515_p0.142828_aggsum_graphseed23_starttrainseed1_endtrainseed6_keepTrue_add1x10_upperTrue_matchTrue_epoch200.yaml',
       'mlp_bs128_1gpu_layer3_transtalklinear_talkmodedense_num64_messagews_sparsity0.342907_p0.064608_aggsum_graphseed10_starttrainseed1_endtrainseed6_keepTrue_add1x10_upperTrue_matchTrue_epoch200.yaml',
       'mlp_bs128_1gpu_layer3_transtalklinear_talkmodedense_num64_messagews_sparsity0.125_p0.004933_aggsum_graphseed3_starttrainseed1_endtrainseed6_keepTrue_add1x10_upperTrue_matchTrue_epoch200.yaml',
       'mlp_bs128_1gpu_layer3_transtalklinear_talkmodedense_num64_messagews_sparsity0.534548_p0.189036_aggsum_graphseed1_starttrainseed1_endtrainseed6_keepTrue_add1x10_upperTrue_matchTr

In [15]:
asu = np.array([[0,1,2],[2,3,0]])
kntl = np.where(asu != 0)
print(asu[kntl])
asu[kntl] = [1,4,5,6]
asu

[1 2 2 3]


array([[0, 1, 4],
       [5, 6, 0]])

In [19]:
wkwk = np.random.choice([0,1], 6)
wkwk.reshape(2,3)

array([[1, 0, 1],
       [1, 0, 1]])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
int(np.sum(wkwk))

4

In [35]:
def CNV(val):
    return '_'.join([str(x).replace(".", "-") for x in val])

In [46]:
for name_file in tmp[x]:
    specs_fixed = [True, False]
    specs_prob = [[0.1, 0.9], [0.2, 0.8], [0.5, 0.5], [0.05, 0.95], [0.01, 0.99]]
    f = open('all/' + name_file, 'r')
    out = [[open('best/' + name_file[:-5].replace("transtalklinear", "transnoisytalklinear") + "_dinamicity_" + str(x) + "_prob" + CNV(y) + ".yaml", 'w+') for y in specs_prob] for x in specs_fixed]
    for line in f.readlines():
        for i in range(len(out)):
            for j in range(len(out[i])):
                out[i][j].write(line.replace("talklinear_transform", "noisytalklinear_transform"))
                if line.strip() == "RGRAPH:":
                    out[i][j].write('  FIXED_DINAMICITY: ' + str(specs_fixed[i]) + '\n')
                    out[i][j].write('  LOSE_EDGE_PROBABILITY: ' + str(specs_prob[j]) + '\n')

In [33]:
asu = [0.1, 0.9]
print(str(asu))

[0.1, 0.9]


In [41]:
asu = "aaabbb"
asu.replace("ab", "")

'aabb'

In [42]:
asu

'aaabbb'